title: Welcome to MUVON
author: murali1308
email: voleti_murali@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Very Glad that you are here, we can discuss multiple technical topics in this site
  Feel free to contribute or comment

# social links
twitter_username: murali1308 # DO NOT include the @ character, or else the build will fail!
github_username:  murali1308 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
